<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ViewUser.aspx.cs" Inherits="ProjectFinal.View.ViewUser" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <a href="HomePage.aspx">Back to HomePage</a>
            <h1>View User</h1>
            <br /> <br />

            <asp:GridView ID="grdUser" runat="server" AutoGenerateColumns="false" AutoGenerateDeleteButton="true" OnRowDeleting="grdUser_RowDeleting">
                <Columns>
                    <asp:BoundField DataField="Username" HeaderText="Username" />
                    <asp:BoundField DataField="Name" HeaderText="Name" />
                    <asp:BoundField DataField="Role.RoleName" HeaderText="Role" />
                    <asp:BoundField DataField="Gender" HeaderText="Gender" />
                    <asp:BoundField DataField="PhoneNumber" HeaderText="Phone Number" />
                    <asp:BoundField DataField="Address" HeaderText="Address" />
                </Columns>
            </asp:GridView>
        </div>
    </form>
</body>
</html>
